# Generated by Django 6.1.1 on 2026-09-24 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='category',
            field=models.CharField(blank=True, choices=[('otp', 'Otp'), ('thank_you', 'Thank You'), ('birthday', 'Birthday'), ('holiday', 'Holiday'), ('welcome', 'Welcome'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='birthday_messages_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='messaging.organization')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.customer'),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('thank_you', 'Thank You'), ('birthday', 'Birthday'), ('holiday', 'Holiday'), ('welcome', 'Welcome'), ('custom', 'Custom')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=480)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='messaging.organization')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagetemplate'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'birthday'], name='messaging_c_organiz_006b2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'phone'), name='uniq_org_customer_phone'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['organization', 'category'], name='messaging_m_organiz_657418_idx'),
        ),
    ]
