# Generated by Django 6.1.1 on 2026-09-28 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='raw_webhook',
            new_name='raw_response',
        ),
        migrations.CreateModel(
            name='SmsPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_pesewas', models.BigIntegerField()),
                ('message_count', models.PositiveIntegerField()),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_pesewas'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_pesewas__gt', 0)), name='smsplan_price_positive')],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='messaging.smsplan'),
        ),
    ]
