# Generated by Django 6.0.7 on 2026-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_sms_plans_and_payment_reference'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='senderid',
            name='uniq_org_sender',
        ),
        migrations.AddField(
            model_name='senderid',
            name='channel',
            field=models.CharField(choices=[('sms', 'Sms'), ('email', 'Email')], default='sms', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(blank=True, choices=[('otp', 'Otp'), ('sms', 'Sms'), ('thank_you', 'Thank You'), ('birthday', 'Birthday'), ('holiday', 'Holiday'), ('welcome', 'Welcome'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='recipient',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='senderid',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AddConstraint(
            model_name='senderid',
            constraint=models.UniqueConstraint(fields=('organization', 'channel', 'name'), name='uniq_org_sender'),
        ),
    ]
